const STORAGE_KEY="minGymAppData_v142";
const defaultData={plans:[],sessions:[],exerciseBank:[]};
let data=loadData(),draftPlan=emptyPlan(),editingPlanId=null,activeSession=null,sessionExerciseDraft=null,replacingExerciseIndex=null;
const el=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{setupTabs();setupButtons();renderAll()});
function id(){return"id-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,8)}
function clone(v){return JSON.parse(JSON.stringify(v))}
function emptyPlan(){return{id:id(),name:"",exercises:[]}}
function loadData(){try{const s=localStorage.getItem(STORAGE_KEY)||localStorage.getItem("minGymAppData_v141")||localStorage.getItem("minGymAppData_v14")||localStorage.getItem("minGymAppData_v13")||localStorage.getItem("minGymAppData_v12");if(!s)return clone(defaultData);const r=JSON.parse(s),plans=Array.isArray(r.plans)?r.plans:[],sessions=Array.isArray(r.sessions)?r.sessions:[],bank=[...(r.exerciseBank||[]),...plans.flatMap(p=>p.exercises||[]).map(e=>e.name),...sessions.flatMap(s=>s.exercises||[]).map(e=>e.name)];return{plans,sessions,exerciseBank:unique(bank)}}catch{return clone(defaultData)}}
function unique(a){const m=new Map();a.forEach(n=>{const c=String(n||"").trim();if(c)m.set(c.toLowerCase(),c)});return[...m.values()].sort((a,b)=>a.localeCompare(b,"sv"))}
function remember(n){data.exerciseBank=unique([...data.exerciseBank,n])}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function setupTabs(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));b.classList.add("active");el(b.dataset.tab).classList.add("active")})}
function setupButtons(){el("addExerciseBtn").onclick=()=>{draftPlan.exercises.push({id:id(),name:"",sets:[{id:id(),weight:"",reps:""}]});renderDraft()};el("savePlanBtn").onclick=savePlan;el("cancelEditBtn").onclick=cancelEdit;el("startSessionBtn").onclick=startSession;el("saveSessionBtn").onclick=saveSession;el("addSessionExerciseBtn").onclick=()=>openSessionForm(null);el("addSessionExerciseSetBtn").onclick=()=>{sessionExerciseDraft.sets.push({id:id(),weight:"",reps:""});renderSessionForm()};el("saveSessionExerciseBtn").onclick=saveSessionExercise;el("cancelSessionExerciseBtn").onclick=closeSessionForm}
function renderAll(){renderEditorMode();renderDraft();renderPlans();renderPlanSelect();renderSession();renderHistory();renderPB();el("exerciseSuggestions").innerHTML=data.exerciseBank.map(n=>`<option value="${esc(n)}"></option>`).join("")}
function renderEditorMode(){const e=!!editingPlanId;el("planEditorTitle").textContent=e?"Redigera upplägg":"Skapa upplägg";el("planEditorHelp").innerHTML=e?'<span class="editing-badge">Redigerar standardupplägg</span><br>Historiken påverkas inte.':"Här administrerar du dina standardupplägg.";el("savePlanBtn").textContent=e?"Spara ändringar":"Spara upplägg";el("cancelEditBtn").classList.toggle("hidden",!e)}
function renderDraft(){el("planName").value=draftPlan.name;el("exerciseEditor").innerHTML=draftPlan.exercises.map((e,ei)=>`<div class="exercise-editor"><div class="exercise-name-row"><div><label>Övning</label><input list="exerciseSuggestions" value="${esc(e.name)}" placeholder="Exempel: Marklyft" oninput="draftPlan.exercises[${ei}].name=this.value"></div><button class="danger" onclick="removeDraftExercise(${ei})">Ta bort</button></div>${e.sets.map((s,si)=>`<div class="set-row"><div class="set-index">${si+1}</div><input type="number" inputmode="decimal" value="${s.weight}" placeholder="kg" oninput="draftPlan.exercises[${ei}].sets[${si}].weight=this.value"><input type="number" inputmode="numeric" value="${s.reps}" placeholder="reps" oninput="draftPlan.exercises[${ei}].sets[${si}].reps=this.value"><button class="danger" onclick="removeDraftSet(${ei},${si})">×</button></div>`).join("")}<button class="secondary full" onclick="addDraftSet(${ei})">+ Lägg till set</button></div>`).join("")}
window.addDraftSet=ei=>{draftPlan.exercises[ei].sets.push({id:id(),weight:"",reps:""});renderDraft()};
window.removeDraftSet=(ei,si)=>{draftPlan.exercises[ei].sets.splice(si,1);if(!draftPlan.exercises[ei].sets.length)draftPlan.exercises[ei].sets.push({id:id(),weight:"",reps:""});renderDraft()};
window.removeDraftExercise=ei=>{draftPlan.exercises.splice(ei,1);renderDraft()};
function savePlan(){const name=el("planName").value.trim(),ex=draftPlan.exercises.map(e=>({...e,name:String(e.name||"").trim(),sets:e.sets.filter(s=>String(s.weight??"")!==""||String(s.reps??"")!=="").map(s=>({id:s.id||id(),weight:Number(s.weight||0),reps:Number(s.reps||0)}))})).filter(e=>e.name&&e.sets.length);if(!name)return alert("Skriv ett namn på upplägget.");if(!ex.length)return alert("Lägg till minst en övning med minst ett set.");ex.forEach(e=>remember(e.name));if(editingPlanId){const i=data.plans.findIndex(p=>p.id===editingPlanId);data.plans[i]={...data.plans[i],name,exercises:ex};editingPlanId=null}else data.plans.push({id:id(),name,exercises:ex});draftPlan=emptyPlan();save();renderAll()}
window.editPlan=pid=>{const p=data.plans.find(x=>x.id===pid);if(!p)return;editingPlanId=pid;draftPlan=clone(p);renderAll();document.querySelector('[data-tab="plans"]').click();scrollTo({top:0,behavior:"smooth"})};
function cancelEdit(){editingPlanId=null;draftPlan=emptyPlan();renderAll()}
window.deletePlan=i=>{if(confirm("Vill du ta bort upplägget?")){data.plans.splice(i,1);save();renderAll()}};
function renderPlans(){el("plansList").innerHTML=data.plans.length?data.plans.map((p,i)=>`<div class="plan-item"><div class="exercise-header"><div><h3>${esc(p.name)}</h3><p class="plan-summary">${p.exercises.length} övningar · ${p.exercises.reduce((a,e)=>a+e.sets.length,0)} set</p></div><div class="plan-actions"><button class="secondary" onclick="editPlan('${p.id}')">Redigera</button><button class="danger" onclick="deletePlan(${i})">Ta bort</button></div></div><div class="plan-exercises">${p.exercises.map(e=>`<div class="plan-exercise-line"><span>${esc(e.name)}</span><span>${e.sets.length} set</span></div>`).join("")}</div></div>`).join(""):'<div class="empty">Inga upplägg skapade ännu.</div>'}
function renderPlanSelect(){if(!data.plans.length){el("sessionPlanSelect").innerHTML='<option>Skapa ett upplägg först</option>';el("startSessionBtn").disabled=true}else{el("startSessionBtn").disabled=false;el("sessionPlanSelect").innerHTML=data.plans.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join("")}}
function startSession(){const p=data.plans.find(x=>x.id===el("sessionPlanSelect").value);if(!p)return;activeSession={id:id(),planId:p.id,planName:p.name,date:new Date().toISOString().slice(0,10),exercises:p.exercises.map(e=>({id:id(),templateExerciseId:e.id,name:e.name,done:false,updateStandard:false,sets:e.sets.map(s=>({id:id(),weight:s.weight,reps:s.reps}))}))};el("saveConfirmation").classList.add("hidden");closeSessionForm();renderSession()}
function renderSession(){const c=el("activeSessionCard");if(!activeSession){c.classList.add("hidden");return}c.classList.remove("hidden");el("activeSessionTitle").textContent=activeSession.planName;el("activeSessionDate").textContent=activeSession.date;const done=activeSession.exercises.filter(e=>e.done).length;el("sessionProgress").textContent=`${done}/${activeSession.exercises.length} klara`;el("activeExercises").innerHTML=activeSession.exercises.map((e,ei)=>`<div class="session-exercise ${e.done?"done":""}"><div class="exercise-header"><label class="checkbox-row"><input type="checkbox" ${e.done?"checked":""} onchange="toggleDone(${ei},this.checked)"><span><strong>${esc(e.name)}</strong></span></label><div class="session-actions"><button class="secondary" onclick="replaceExercise(${ei})">Ersätt</button><button class="danger" onclick="removeExercise(${ei})">Ta bort</button></div></div>${e.sets.map((s,si)=>`<div class="set-row"><div class="set-index">${si+1}</div><input type="number" inputmode="decimal" value="${s.weight}" oninput="activeSession.exercises[${ei}].sets[${si}].weight=Number(this.value||0)"><input type="number" inputmode="numeric" value="${s.reps}" oninput="activeSession.exercises[${ei}].sets[${si}].reps=Number(this.value||0)"><button class="danger" onclick="removeSessionSet(${ei},${si})">×</button></div>`).join("")}<button class="secondary full" onclick="addSessionSet(${ei})">+ Lägg till set</button></div>`).join("");const eligible=activeSession.exercises.map((e,i)=>({e,i})).filter(x=>x.e.done&&x.e.templateExerciseId);el("updateStandardOptions").innerHTML=eligible.length?eligible.map(x=>`<label class="checkbox-row"><input type="checkbox" ${x.e.updateStandard?"checked":""} onchange="activeSession.exercises[${x.i}].updateStandard=this.checked"><span>Uppdatera standard för ${esc(x.e.name)}</span></label>`).join(""):'<div class="empty">Markera en standardövning som genomförd för att kunna uppdatera den.</div>'}
window.toggleDone=(i,v)=>{activeSession.exercises[i].done=v;if(!v)activeSession.exercises[i].updateStandard=false;renderSession()};
window.addSessionSet=i=>{activeSession.exercises[i].sets.push({id:id(),weight:0,reps:0});renderSession()};
window.removeSessionSet=(i,j)=>{activeSession.exercises[i].sets.splice(j,1);if(!activeSession.exercises[i].sets.length)activeSession.exercises[i].sets.push({id:id(),weight:0,reps:0});renderSession()};
window.removeExercise=i=>{if(confirm("Ta bort övningen från dagens pass? Standardupplägget påverkas inte.")){activeSession.exercises.splice(i,1);renderSession()}};
window.replaceExercise=i=>openSessionForm(i);
function openSessionForm(i){replacingExerciseIndex=Number.isInteger(i)?i:null;sessionExerciseDraft=replacingExerciseIndex!==null?{name:"",sets:activeSession.exercises[i].sets.map(s=>({id:id(),weight:s.weight,reps:s.reps}))}:{name:"",sets:[{id:id(),weight:"",reps:""}]};el("sessionExerciseFormTitle").textContent=replacingExerciseIndex!==null?`Ersätt ${activeSession.exercises[i].name}`:"Lägg till övning";el("sessionExerciseForm").classList.remove("hidden");renderSessionForm();el("sessionExerciseName").focus()}
function closeSessionForm(){sessionExerciseDraft=null;replacingExerciseIndex=null;el("sessionExerciseForm").classList.add("hidden");el("sessionExerciseName").value=""}
function renderSessionForm(){if(!sessionExerciseDraft)return;el("sessionExerciseName").value=sessionExerciseDraft.name;el("sessionExerciseName").oninput=e=>sessionExerciseDraft.name=e.target.value;el("sessionExerciseSets").innerHTML=sessionExerciseDraft.sets.map((s,i)=>`<div class="set-row"><div class="set-index">${i+1}</div><input type="number" inputmode="decimal" value="${s.weight}" placeholder="kg" oninput="sessionExerciseDraft.sets[${i}].weight=this.value"><input type="number" inputmode="numeric" value="${s.reps}" placeholder="reps" oninput="sessionExerciseDraft.sets[${i}].reps=this.value"><button class="danger" onclick="removeSessionDraftSet(${i})">×</button></div>`).join("")}
window.removeSessionDraftSet=i=>{sessionExerciseDraft.sets.splice(i,1);if(!sessionExerciseDraft.sets.length)sessionExerciseDraft.sets.push({id:id(),weight:"",reps:""});renderSessionForm()};
function saveSessionExercise(){const name=String(sessionExerciseDraft.name||"").trim(),sets=sessionExerciseDraft.sets.filter(s=>String(s.weight??"")!==""||String(s.reps??"")!=="").map(s=>({id:id(),weight:Number(s.weight||0),reps:Number(s.reps||0)}));if(!name)return alert("Skriv namnet på övningen.");if(!sets.length)return alert("Lägg till minst ett set.");remember(name);const ex={id:id(),templateExerciseId:null,name,done:false,updateStandard:false,sets};if(replacingExerciseIndex!==null)activeSession.exercises[replacingExerciseIndex]=ex;else activeSession.exercises.push(ex);save();closeSessionForm();renderAll()}
function saveSession(){const completed=activeSession.exercises.filter(e=>e.done);if(!completed.length)return alert("Markera minst en övning som genomförd innan du sparar passet.");if(completed.length<activeSession.exercises.length&&!confirm(`Du har markerat ${completed.length} av ${activeSession.exercises.length} övningar som genomförda. Endast de genomförda övningarna sparas. Vill du fortsätta?`))return;data.sessions.unshift({...clone(activeSession),exercises:clone(completed)});const p=data.plans.find(x=>x.id===activeSession.planId);if(p)completed.forEach(se=>{if(se.updateStandard&&se.templateExerciseId){const te=p.exercises.find(x=>x.id===se.templateExerciseId);if(te)te.sets=se.sets.map(s=>({id:id(),weight:Number(s.weight||0),reps:Number(s.reps||0)}))}});completed.forEach(e=>remember(e.name));const ec=completed.length,sc=completed.reduce((a,e)=>a+e.sets.length,0),date=activeSession.date;activeSession=null;closeSessionForm();save();renderAll();el("saveConfirmation").innerHTML=`<strong>Pass sparat ✅</strong><p class="muted">Genomförda övningar: ${ec}<br>Totalt antal set: ${sc}<br>Datum: ${date}</p>`;el("saveConfirmation").classList.remove("hidden")}
function renderHistory(){el("historyList").innerHTML=data.sessions.length?data.sessions.map(s=>`<div class="history-item"><div class="history-date">${s.date}</div><p class="muted">${esc(s.planName)}</p>${(s.exercises||[]).map(e=>`<div class="history-exercise"><strong>${esc(e.name)}</strong><div class="history-sets">${(e.sets||[]).map(x=>`${x.weight} kg × ${x.reps}`).join("<br>")}</div></div>`).join("")}</div>`).join(""):'<div class="empty">Ingen historik ännu.</div>'}
function renderPB(){const p={};data.sessions.forEach(s=>(s.exercises||[]).forEach(e=>(e.sets||[]).forEach(x=>{const w=Number(x.weight||0);if(!p[e.name]||w>p[e.name].weight)p[e.name]={exercise:e.name,weight:w,reps:Number(x.reps||0),date:s.date}})));const v=Object.values(p).sort((a,b)=>a.exercise.localeCompare(b.exercise,"sv"));el("pbList").innerHTML=v.length?v.map(x=>`<div class="pb-item"><strong>${esc(x.exercise)}</strong><div class="pb-lift">${x.weight} kg × ${x.reps}</div><div class="pb-meta">${x.date}</div></div>`).join(""):'<div class="empty">Inga personbästan ännu.</div>'}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
